# Use the official ubuntu image
FROM ubuntu:latest

# Update APT package lists
RUN apt-get update

# Upgrage currently installed software with automatic "yes" response
RUN apt-get upgrade -y

# Echo "Hello, World!" when the container runs
CMD echo "Hello, World!"
